# Which language are we using?
language: r

# Cache installed packages to speed up build times
cache: packages

# Compression can be improved if we resave data on build
r_build_args: --resave-data

# CHeck for code test coverage with covr
r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'